include:
  - project: 'city-of-helsinki/kuva/ci-cd-config/ci-configuration'
    ref: v2
    file: '/.gitlab-ci-template.yml'

variables:
  SERVICE_PORT: 80

build-review:
  # These variables are available only for review env and are merged with the general variables defined above.
  extends: .build
  variables:
    DOCKER_IMAGE_NAME: "$CI_PROJECT_NAME-review"
    DOCKER_BUILD_ARG_REACT_APP_ENVIRONMENT: 'review'
    DOCKER_BUILD_ARG_REACT_APP_PROFILE_LINK: "https://profiili.test.kuva.hel.ninja/loginsso"
    DOCKER_BUILD_ARG_REACT_APP_OIDC_AUTHORITY: "https://tunnistamo.test.kuva.hel.ninja"
    DOCKER_BUILD_ARG_REACT_APP_OIDC_CLIENT_ID: "review-$TF_PROJECT_NAME_SLUG-$CI_COMMIT_REF_SLUG"
    DOCKER_BUILD_ARG_REACT_APP_OIDC_SCOPE: "openid https://api.hel.fi/auth/jassariapi https://api.hel.fi/auth/helsinkiprofile"
    DOCKER_BUILD_ARG_REACT_APP_PROFILE_GRAPHQL: "https://jassari-federation.test.kuva.hel.ninja/"
    DOCKER_BUILD_ARG_REACT_APP_BASE_URL: "https://$TF_PROJECT_NAME_SLUG-$CI_ENVIRONMENT_SLUG.$KUBE_INGRESS_BASE_DOMAIN"
    DOCKER_BUILD_ARG_REACT_APP_ADMIN_URL: "https://jassari-admin.test.kuva.hel.ninja/"

  only:
    refs:
      - external_pull_requests

build-staging:
  extends: .build
  variables:
    DOCKER_IMAGE_NAME: "$CI_PROJECT_NAME-staging"
    DOCKER_BUILD_ARG_REACT_APP_ENVIRONMENT: 'staging'
    DOCKER_BUILD_ARG_REACT_APP_PROFILE_LINK: "https://profiili.test.kuva.hel.ninja/loginsso"
    DOCKER_BUILD_ARG_REACT_APP_OIDC_AUTHORITY: "https://api.hel.fi/sso-test/"
    DOCKER_BUILD_ARG_REACT_APP_OIDC_CLIENT_ID: "https://api.hel.fi/auth/jassari"
    DOCKER_BUILD_ARG_REACT_APP_OIDC_SCOPE: "openid https://api.hel.fi/auth/jassariapi https://api.hel.fi/auth/helsinkiprofile"
    DOCKER_BUILD_ARG_REACT_APP_PROFILE_GRAPHQL: "https://jassari-federation.test.kuva.hel.ninja/"
    DOCKER_BUILD_ARG_REACT_APP_BASE_URL: "https://jassari.test.kuva.hel.ninja"
    DOCKER_BUILD_ARG_REACT_APP_ADMIN_URL: "https://jassari-admin.test.kuva.hel.ninja/"
  only:
    refs:
      - develop

build-production:
  extends: .build
  variables:
    DOCKER_IMAGE_NAME: "$CI_PROJECT_NAME-production"
    DOCKER_BUILD_ARG_REACT_APP_ENVIRONMENT: 'production'
    DOCKER_BUILD_ARG_REACT_APP_PROFILE_LINK: "https://profiili.hel.fi/loginsso"
    DOCKER_BUILD_ARG_REACT_APP_OIDC_AUTHORITY: "https://api.hel.fi/sso/"
    DOCKER_BUILD_ARG_REACT_APP_OIDC_CLIENT_ID: "https://id.hel.fi/auth/clients/jassariui-prod"
    DOCKER_BUILD_ARG_REACT_APP_OIDC_SCOPE: "openid https://api.hel.fi/auth/jassariapi https://api.hel.fi/auth/helsinkiprofile"
    DOCKER_BUILD_ARG_REACT_APP_PROFILE_GRAPHQL: "https://jassari-federation.prod.kuva.hel.ninja/"
    DOCKER_BUILD_ARG_REACT_APP_BASE_URL: "https://jassari.hel.fi"
    DOCKER_BUILD_ARG_REACT_APP_ADMIN_URL: "https://jassari-admin.hel.fi/"
  only:
    refs:
      - master
      # this regexp will match release-tags
      - /^release-.*$/

review:
  variables:
    DOCKER_IMAGE_NAME: "$CI_PROJECT_NAME-review"
    POSTGRES_ENABLED: 0
  script:
    - echo "review client \"review-$TF_PROJECT_NAME_SLUG-$CI_COMMIT_REF_SLUG\""
    - NAMESPACE=tunnistamo-qa kubectl get pod -l "track=staging" --namespace=$NAMESPACE -o jsonpath='\{.items[0].metadata.name\}' | xargs -I\{\} kubectl exec --namespace=$NAMESPACE \{\} -- uname -a
  
# This will enable staging ci-pipeline
staging:
  variables:
    DOCKER_IMAGE_NAME: "$CI_PROJECT_NAME-staging"
  only:
    refs:
      - develop

production:
  variables:
    DOCKER_IMAGE_NAME: "$CI_PROJECT_NAME-production"
