name: Azure DevOps review tunnistamo
on: [pull_request]

env:
  CONTAINER_REGISTRY: ghcr.io
  CONTAINER_REGISTRY_USER: ${{ secrets.GHCR_CONTAINER_REGISTRY_USER }}
  CONTAINER_REGISTRY_PASSWORD: ${{ secrets.GHCR_TOKEN }}
  CONTAINER_REGISTRY_REPO: ghcr.io/city-of-helsinki/${{ github.event.repository.name }}
  REPO_NAME: ${{ github.event.repository.name }}
  KUBECONFIG_RAW: ${{ secrets.KUBECONFIG_RAW }}
  BASE_DOMAIN: ${{ secrets.BASE_DOMAIN_STAGING }}
  TUNNISTAMO_NAMESPACE: 'tunnistamo-qa'
  CALLBACK_PATH: '/callback'
  RESPONSE_TYPES: '"id_token token"'
  LOGIN_METHODS: 'github helusername'
  # review name and url should match to review name on DevOps pipeline
  REVIEW_NAMESPACE: youth-membership-ui-pr${{github.event.pull_request.number}}
  ENVIRONMENT_URL: https://youth-membership-ui-pr${{github.event.pull_request.number}}.dev.hel.ninja

  API_SCOPE_JASSARI: https://api.hel.fi/auth/jassariapi
  API_SCOPE_HELSINKIPROFILE: https://api.hel.fi/auth/helsinkiprofile

jobs:

  review:
    runs-on: ubuntu-latest
    name: Tunnistamo setup for DevOps review
    steps:
      - name: Setup kubectl
        run: |
            echo "${KUBECONFIG_RAW}" > $(pwd)/kubeconfig
            echo "KUBECONFIG=$(pwd)/kubeconfig" >> $GITHUB_ENV
        shell: bash
        env:
          KUBECONFIG_RAW: ${{ env.KUBECONFIG_RAW}}

      - name: Get Tunnistamo pod
        run:  |
          TUNNISTAMO_POD=$(kubectl get po -n "${{ env.TUNNISTAMO_NAMESPACE }}" -l app=master-tunnistamo -l track=staging --field-selector status.phase=Running -o jsonpath='{.items[0].metadata.name}')
          echo "Using Tunnistamo pod $TUNNISTAMO_POD"
          echo "TUNNISTAMO_POD=$TUNNISTAMO_POD" >> $GITHUB_ENV
        shell: bash

    - name: Add new client
      run: |
        kubectl exec -n "${{ env.TUNNISTAMO_NAMESPACE }}" "${TUNNISTAMO_POD}" -- ./manage.py add_oidc_client --name "${{ env.REVIEW_NAMESPACE }}" --response_types ${{ env.RESPONSE_TYPES }} --redirect_uris "${{ env.ENVIRONMENT_URL }}${{ env.CALLBACK_PATH }}" --client_id "${{ env.REVIEW_NAMESPACE }}" --site_type dev --login_methods ${{ env.LOGIN_METHODS }}
        echo "Added client ${{ env.REVIEW_NAMESPACE }} to Tunnistamo"
      shell: bash
    
    - name: Map client to Jassari API scope
      run: | 
        kubectl exec -n "${{ env.TUNNISTAMO_NAMESPACE }}" "${TUNNISTAMO_POD}" -- ./manage.py add_oidc_client_to_api_scope --api_scope_identifier "${{ env.API_SCOPE_JASSARI }}" --client_id "${{ env.REVIEW_NAMESPACE }}" 
        echo "Mapped client ${{ env.REVIEW_NAMESPACE }} to API Scope ${{ env.API_SCOPE_JASSARI }}"
      shell: bash

    - name: Map client to Helösinkiprofile API scope
      run: | 
        kubectl exec -n "${{ env.TUNNISTAMO_NAMESPACE }}" "${TUNNISTAMO_POD}" -- ./manage.py add_oidc_client_to_api_scope --api_scope_identifier "${{ env.API_SCOPE_HELSINKIPROFILE }}" --client_id "${{ env.REVIEW_NAMESPACE }}" 
        echo "Mapped client ${{ env.REVIEW_NAMESPACE }} to API Scope ${{ env.API_SCOPE_HELSINKIPROFILE }}"
      shell: bash
